"""Optional live CloudPSS closed-loop tests for generated unified models."""

from __future__ import annotations

import os
import time
from copy import deepcopy
from datetime import datetime

import pytest

from cloudpss_skills_v2.tests.test_unified_to_cloudpss_draft import build_three_bus_model
from cloudpss_skills_v2.powerapi.adapters.cloudpss.model_draft import (
    CloudPSSModelWriter,
    UnifiedToCloudPSSDraftConverter,
)
from cloudpss_skills_v2.powerapi.adapters.cloudpss.model_inventory import (
    CloudPSSInventoryExtractor,
)


RUN_LIVE_GENERATION = os.environ.get("CLOUDPSS_V2_RUN_LIVE_MODEL_GENERATION") == "1"


def _wait_for_powerflow(job, timeout_s: int = 120) -> int:
    waited = 0
    while waited < timeout_s:
        status = job.status()
        if status in (1, 2):
            return status
        time.sleep(2)
        waited += 2
    return job.status()


@pytest.mark.cloudpss
@pytest.mark.integration
@pytest.mark.skipif(
    not RUN_LIVE_GENERATION,
    reason="set CLOUDPSS_V2_RUN_LIVE_MODEL_GENERATION=1 to create live CloudPSS models",
)
def test_unified_to_cloudpss_live_create_fetch_inventory_and_powerflow(
    cloudpss_token,
    cloudpss_api_url,
    cloudpss_model_rid,
    monkeypatch,
):
    if not cloudpss_token:
        pytest.skip("CloudPSS token not available")

    from cloudpss import Model, setToken

    monkeypatch.setenv("CLOUDPSS_API_URL", cloudpss_api_url)
    monkeypatch.setenv("CLOUDPSS_TOKEN", cloudpss_token)
    setToken(cloudpss_token)
    base_model = Model.fetch(cloudpss_model_rid, baseUrl=cloudpss_api_url)
    generated_model = Model(deepcopy(base_model.toJSON()))
    generated_model.name = "Codex unified-to-CloudPSS live loop"
    generated_model.description = (
        "Generated by cloudpss_skills_v2 live closed-loop test from PowerSystemModel"
    )

    draft = UnifiedToCloudPSSDraftConverter().convert(build_three_bus_model())
    created = CloudPSSModelWriter().write(
        generated_model,
        draft,
        clear_existing=True,
    )

    local_inventory = CloudPSSInventoryExtractor().extract(generated_model)
    local_diagnostics = local_inventory.diagnostics()
    assert len(created) == len(draft.components)
    assert local_diagnostics["status"] == "pass"
    assert local_diagnostics["component_type_counts"] == {
        "bus": 3,
        "branch": 1,
        "transformer": 1,
        "load": 1,
        "generator": 2,
    }

    key = "codex_v2_unified_cloudpss_loop_" + datetime.now().strftime("%Y%m%d_%H%M%S")
    save_result = generated_model.save(key)
    generated_rid = (
        save_result.get("data", {}).get("createModel", {}).get("rid")
        or save_result.get("data", {}).get("updateModel", {}).get("rid")
        or save_result.get("rid")
        or generated_model.rid
    )
    assert generated_rid and generated_rid.startswith("model/")

    fetched_model = Model.fetch(generated_rid, baseUrl=cloudpss_api_url)
    fetched_inventory = CloudPSSInventoryExtractor().extract(fetched_model)
    fetched_diagnostics = fetched_inventory.diagnostics()
    assert fetched_diagnostics["status"] == "pass"
    assert fetched_diagnostics["component_type_counts"]["bus"] == 3
    assert fetched_diagnostics["component_type_counts"]["branch"] == 1
    assert fetched_diagnostics["component_type_counts"]["transformer"] == 1
    assert fetched_diagnostics["parameter_coverage"]["line_with_r_x_count"] == 1
    assert fetched_diagnostics["parameter_coverage"]["transformer_with_x_count"] == 1

    try:
        job = fetched_model.runPowerFlow(baseUrl=cloudpss_api_url)
        status = _wait_for_powerflow(job)
    except Exception as exc:
        pytest.fail(
            f"generated model saved and fetched but runPowerFlow could not start "
            f"for {generated_rid}: {type(exc).__name__}: {exc}"
        )

    assert status == 1, f"generated CloudPSS power flow did not complete: rid={generated_rid}, status={status}"
    result = job.result
    assert result is not None
    assert result.getBuses() is not None
